package graphics;

import java.io.IOException;
import java.util.List;

import javax.swing.JOptionPane;

import model.Game;
import network.NetClient;
import network.NetworkEvent;
import network.NetworkObserver;
import utils.Pair;
import utils.Point2D;
import utils.Util;

public class ClientFrame extends javax.swing.JFrame implements NetworkObserver {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = -1931892390969434886L;
	
	boolean isInGame=false;


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        mainLayeredPane = new javax.swing.JLayeredPane();
        startPanel = new javax.swing.JPanel();
        startPanelLayeredPane = new javax.swing.JLayeredPane();
        infoPanel = new javax.swing.JPanel();
        infoPanelContent = new javax.swing.JPanel();
        usernameField = new javax.swing.JTextField();
        serveripField = new javax.swing.JTextField();
        serverportField = new javax.swing.JTextField();
        serveripLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        serverportLabel = new javax.swing.JLabel();
        configButton = new javax.swing.JButton();
        playButton = new javax.swing.JButton();
        configPanel = new javax.swing.JPanel();
        configPanelContent = new javax.swing.JPanel();
        Forward = new javax.swing.JLabel();
        Left = new javax.swing.JLabel();
        Backward = new javax.swing.JLabel();
        Right = new javax.swing.JLabel();
        forwardField = new javax.swing.JOptionPane("Z");
        backwardField = new javax.swing.JOptionPane("NONE");
        leftField = new javax.swing.JOptionPane("Q");
        rightField = new javax.swing.JOptionPane("D");
        backButton = new javax.swing.JButton();
        escapePanel = new javax.swing.JPanel();
        menuLabel = new javax.swing.JLabel();
        configurationButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        continueButton = new javax.swing.JButton();
        
        
        gamePanel = new MyComponent();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mario Kart 2.0 - Kevin & Firat Prod.");
        setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        /*
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });*/

        mainLayeredPane.setPreferredSize(this.getPreferredSize());
        mainLayeredPane.setLayout(new java.awt.CardLayout());

        startPanelLayeredPane.setLayout(new java.awt.CardLayout());

        infoPanel.setBackground(new java.awt.Color(51, 51, 51));

        infoPanelContent.setBackground(new java.awt.Color(51, 51, 51));

        usernameField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        serveripField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        serverportField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        serveripLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        serveripLabel.setForeground(new java.awt.Color(255, 255, 255));
        serveripLabel.setText("Server IP");

        usernameLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        usernameLabel.setText("Username");

        serverportLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        serverportLabel.setForeground(new java.awt.Color(255, 255, 255));
        serverportLabel.setText("Server Port");

        configButton.setBackground(new java.awt.Color(51, 51, 51));
        configButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        configButton.setForeground(new java.awt.Color(255, 255, 255));
        configButton.setText("Configuration");
        configButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        configButton.setMargin(new java.awt.Insets(3, 14, 3, 14));
        configButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                configButtonMouseClicked(evt);
            }
        });

        playButton.setBackground(new java.awt.Color(51, 51, 51));
        playButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        playButton.setForeground(new java.awt.Color(255, 255, 255));
        playButton.setText("Play");
        playButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        playButton.setMargin(new java.awt.Insets(3, 14, 3, 14));
        playButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout infoPanelContentLayout = new javax.swing.GroupLayout(infoPanelContent);
        infoPanelContent.setLayout(infoPanelContentLayout);
        infoPanelContentLayout.setHorizontalGroup(
            infoPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelContentLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(infoPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(configButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(infoPanelContentLayout.createSequentialGroup()
                            .addGroup(infoPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(serveripLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(serverportLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(122, 122, 122)
                            .addGroup(infoPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(serverportField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(serveripField))))
                    .addGroup(infoPanelContentLayout.createSequentialGroup()
                        .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        infoPanelContentLayout.setVerticalGroup(
            infoPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelContentLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(infoPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infoPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serveripLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serveripField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infoPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serverportLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serverportField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(configButton)
                .addGap(18, 18, 18)
                .addComponent(playButton)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPanelLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(infoPanelContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(infoPanelContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        startPanelLayeredPane.add(infoPanel, "card2");

        configPanel.setBackground(new java.awt.Color(51, 51, 51));

        configPanelContent.setBackground(new java.awt.Color(51, 51, 51));

        Forward.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Forward.setForeground(new java.awt.Color(255, 255, 255));
        Forward.setText("Forward");

        Left.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Left.setForeground(new java.awt.Color(255, 255, 255));
        Left.setText("Left");

        Backward.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Backward.setForeground(new java.awt.Color(255, 255, 255));
        Backward.setText("Backward");

        Right.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Right.setForeground(new java.awt.Color(255, 255, 255));
        Right.setText("Right");

        forwardField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        backwardField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        leftField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        rightField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        backButton.setBackground(new java.awt.Color(51, 51, 51));
        backButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        backButton.setMargin(new java.awt.Insets(3, 14, 3, 14));
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout configPanelContentLayout = new javax.swing.GroupLayout(configPanelContent);
        configPanelContent.setLayout(configPanelContentLayout);
        configPanelContentLayout.setHorizontalGroup(
            configPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configPanelContentLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(configPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Left, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(configPanelContentLayout.createSequentialGroup()
                        .addGroup(configPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Forward, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Backward, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Right, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(128, 128, 128)
                        .addGroup(configPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rightField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(leftField)
                            .addComponent(forwardField)
                            .addComponent(backwardField)))
                    .addComponent(backButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        configPanelContentLayout.setVerticalGroup(
            configPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configPanelContentLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(configPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(forwardField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Forward, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(configPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Backward, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backwardField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(configPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Left, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leftField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(configPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Right, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(backButton)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout configPanelLayout = new javax.swing.GroupLayout(configPanel);
        configPanel.setLayout(configPanelLayout);
        configPanelLayout.setHorizontalGroup(
            configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(configPanelContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        configPanelLayout.setVerticalGroup(
            configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configPanelLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(configPanelContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        startPanelLayeredPane.add(configPanel, "card3");

        javax.swing.GroupLayout startPanelLayout = new javax.swing.GroupLayout(startPanel);
        startPanel.setLayout(startPanelLayout);
        startPanelLayout.setHorizontalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startPanelLayeredPane)
        );
        startPanelLayout.setVerticalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startPanelLayeredPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        mainLayeredPane.add(startPanel, "card2");

        gamePanel.setBackground(new java.awt.Color(102, 102, 102));


        escapePanel.setBackground(new java.awt.Color(255, 255, 255));
        escapePanel.setForeground(new java.awt.Color(255, 255, 255));
        escapePanel.setOpaque(false);

        menuLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        menuLabel.setForeground(new java.awt.Color(255, 255, 255));
        menuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuLabel.setText("MENU");

        configurationButton.setBackground(new java.awt.Color(51, 51, 51));
        configurationButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        configurationButton.setForeground(new java.awt.Color(255, 255, 255));
        configurationButton.setText("Configuration");
        configurationButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        configurationButton.setMargin(new java.awt.Insets(3, 14, 3, 14));
        configurationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                configurationButtonMouseClicked(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(51, 51, 51));
        exitButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("Exit");
        exitButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        exitButton.setMargin(new java.awt.Insets(3, 14, 3, 14));
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
        });

        continueButton.setBackground(new java.awt.Color(51, 51, 51));
        continueButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        continueButton.setForeground(new java.awt.Color(255, 255, 255));
        continueButton.setText("Continue");
        continueButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        continueButton.setMargin(new java.awt.Insets(3, 14, 3, 14));
        continueButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                continueButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout escapePanelLayout = new javax.swing.GroupLayout(escapePanel);
        escapePanel.setLayout(escapePanelLayout);
        escapePanelLayout.setHorizontalGroup(
            escapePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(escapePanelLayout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addGroup(escapePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(configurationButton, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(continueButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(349, Short.MAX_VALUE))
        );
        escapePanelLayout.setVerticalGroup(
            escapePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escapePanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(menuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(configurationButton)
                .addGap(20, 20, 20)
                .addComponent(continueButton)
                .addGap(142, 142, 142)
                .addComponent(exitButton)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout gamePanelLayout = new javax.swing.GroupLayout(gamePanel);
        gamePanel.setLayout(gamePanelLayout);
        gamePanelLayout.setHorizontalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escapePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        gamePanelLayout.setVerticalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escapePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mainLayeredPane.add(gamePanel, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainLayeredPane, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainLayeredPane, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        
        
        /////////////////////////////////////////////////////////////////////////////////
        escapePanel.setVisible(false);
        gamePanel.addKeyListener(new MyKeyListener(this));
        usernameField.setText("hello");
        serveripField.setText("127.0.0.1");
        serverportField.setText("1234");
        
        pack();
    }// </editor-fold>                        
     /*****************************************************************************************/     
    
    private NetClient client=null;
    private Game game;
    
    public ClientFrame() {
        initComponents(); 
    }
    
    private void playButtonMouseClicked(java.awt.event.MouseEvent evt) {
    	if(client!=null) {
			try {
				client.disconnect();
			} catch (IOException e) {
				JOptionPane.showMessageDialog(this, e.getMessage(), "Disconnect Error", JOptionPane.ERROR_MESSAGE);
			}
    	}
    	System.out.println(serveripField.getText());
    	client = new NetClient(serveripField.getText(), Integer.parseInt(serverportField.getText()));
    	client.registerObserver(this);
    	try {
			client.connect(usernameField.getText());
		} catch (IOException e) {
			JOptionPane.showMessageDialog(this, e.getMessage(), "Connection Error", JOptionPane.ERROR_MESSAGE);
		}
    	// chargement button
    	//////////////
    }
    
    public void welcome() {
    	startPanel.setVisible(false);
        escapePanel.setVisible(false);
        gamePanel.setVisible(true);
       	gamePanel.setFocusable(true);
       	gamePanel.requestFocus();
        isInGame=true;
    }
    
    public void denied() {
    	JOptionPane.showMessageDialog(this, "Username incorrect or already in use.", "Username", JOptionPane.ERROR_MESSAGE);
    }

	@Override
	public void notify(List<NetworkEvent> events) {
		for(NetworkEvent e : events) {
			switch(e.getNetType()) {
			case WELCOMEWAIT:
				welcome();
				// affichage wait
				break;
			case WELCOMEGAME:
				welcome();
				// jeu
				/*
				{
					List<Object> params = e.getParameters();
					String scors =(String) params.get(0); // to display ...
					Point2D coord = Util.getValueInCoord((String) params.get(1));
					List<Pair<String, Integer>> scores;
					game = new Game(scores, coord);
				}
				*/
				break;
			case DENIED:
				denied();
				break;
			case PLAYERLEFT:
				
				break;
			case NEWPLAYER:
				
				break;
			case NEWSESSION:
				List<Object> params = e.getParameters();
				List<Pair<String, Point2D>> coords = Util.getValueInCoords((String) params.get(0));
				Point2D coord = Util.getValueInCoord((String) params.get(1));
				
				game = new Game(coords, coord, this);
				gamePanel.start(game);
				break;
			case WINNER:
				
				gamePanel.stop();
				break;
			default:
				break;
			}
		}
	}
    
	
	public NetClient getClient() {
		return client;
	}

	public javax.swing.JPanel getEscapePanel() {
		// TODO Auto-generated method stub
		return escapePanel;
	}
    
    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {                                        
    	try {
			client.disconnect();
		} catch (IOException e) {
			JOptionPane.showMessageDialog(this, e.getMessage(), "Disconnect Error", JOptionPane.ERROR_MESSAGE);
		}
        isInGame=false;
        gamePanel.setVisible(false);
        startPanel.setVisible(true);
        infoPanel.setVisible(true);
        configPanel.setVisible(false);
    }     
    
    
    
    /******************************************************************************************/
    private void configButtonMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
        infoPanel.setVisible(false);
        configPanel.setVisible(true);
    }                                                                           

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        if(isInGame){
            gamePanel.setVisible(true);
            startPanel.setVisible(false);
        }else{
            configPanel.setVisible(false);
            infoPanel.setVisible(true);
        }
    }                                       
  

    private void continueButtonMouseClicked(java.awt.event.MouseEvent evt) {                                            
        // TODO add your handling code here:
        escapePanel.setVisible(false);
    }                                                                                                                     

    private void configurationButtonMouseClicked(java.awt.event.MouseEvent evt) {                                                 
        // TODO add your handling code here:
        gamePanel.setVisible(false);
        startPanel.setVisible(true);
        configPanel.setVisible(true);
        infoPanel.setVisible(false);
    }                                                

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Backward;
    private javax.swing.JLabel Forward;
    private javax.swing.JLabel Left;
    private javax.swing.JLabel Right;
    private javax.swing.JButton backButton;
    private JOptionPane backwardField;
    private javax.swing.JButton configButton;
    private javax.swing.JPanel configPanel;
    private javax.swing.JPanel configPanelContent;
    private javax.swing.JButton configurationButton;
    private javax.swing.JButton continueButton;
    private javax.swing.JPanel escapePanel;
    private javax.swing.JButton exitButton;
    private JOptionPane forwardField;
    private MyComponent gamePanel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JPanel infoPanelContent;
    private JOptionPane leftField;
    private javax.swing.JLayeredPane mainLayeredPane;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JButton playButton;
    private JOptionPane rightField;
    private javax.swing.JTextField serveripField;
    private javax.swing.JLabel serveripLabel;
    private javax.swing.JTextField serverportField;
    private javax.swing.JLabel serverportLabel;
    private javax.swing.JPanel startPanel;
    private javax.swing.JLayeredPane startPanelLayeredPane;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration                   

}